version: '3.8'

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=micro_db
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Dump20220219.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    image: spring-boot-app:latest
    ports:
      - "8181:8080" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/micro_db?autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

volumes:
  mysql-data: